version: "3.8"

services:
  greeting-app:
    build:
      dockerfile: Dockerfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=admin
    volumes:
      - .:/app
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    entrypoint: npm run start 
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: always
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
