version: "3.8"

services:
  greeting-app:
    build:
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
    volumes:
      - .:/app
    ports:
      - "5051:5050"
    depends_on:
      - db
    entrypoint: npm run start 
    restart: always
  db:
    image: postgres:14.7-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql